# Generated by Django 5.0.6 on 2024-06-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seminar", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seminar",
            old_name="thumnail",
            new_name="thumbnail",
        ),
    ]
