# Generated by Django 5.0.6 on 2024-07-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seminar", "0002_rename_thumnail_seminar_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("video_file", models.FileField(upload_to="seminar_videos/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "seminar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="seminar.seminar",
                    ),
                ),
            ],
        ),
    ]
