# Generated by Django 5.0.6 on 2024-08-14 08:27

import seminar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seminar", "0003_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seminar",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=seminar.models.get_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to=seminar.models.get_video_upload_to),
        ),
    ]
