# Generated by Django 5.0.6 on 2024-08-14 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seminar", "0004_alter_seminar_thumbnail_alter_video_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
